import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer className="text-center text-sm text-gray-500 mt-10 p-4">
  <p>MarketAIPros provides market analytics and educational tools only.</p>
  <p>We do not provide investment, financial, legal, or tax advice.</p>
  <p>Trading involves risk. You are solely responsible for your decisions.</p>
</footer>
    </html>
  );
}
